// <auto-generated />
using DNCEcommerceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DNCEcommerceApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230506013608_AppDBMigrations")]
    partial class AppDBMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DNCEcommerceApi.Data.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<long>("Sku")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Sku")
                        .HasName("AlternateKey_Sku");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DNCEcommerceApi.Data.Models.Warehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<long>("ProductKey")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductKey");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("DNCEcommerceApi.Data.Models.Warehouse", b =>
                {
                    b.HasOne("DNCEcommerceApi.Data.Models.Product", "Product")
                        .WithMany("Warehouses")
                        .HasForeignKey("ProductKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DNCEcommerceApi.Data.Models.Product", b =>
                {
                    b.Navigation("Warehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
